---
title: "Growth Curve Cessation Prediction"
output: html_notebook
---



```{r}
source('../R/models/smoking_cessation_logistic.R')
source('../R/models/smoking_cessation_results_logistic.R')
```



```{r}
set.seed(123)
  
loadRData <- function(fileName){
#loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}
load("../data/processed/pred_imputedord.rda")
m3_covariate <- loadRData('../data/diagnostic/covariate/lca3_predict.rda')
```


```{r}


# all_cores <- parallel::detectCores(logical = FALSE)
# cl <- makePSOCKcluster(all_cores)
# registerDoParallel(cl)

# load data
m3_class_df <- m3_covariate

pred_set <- build_predictor_set(pred_imputed, m3_class_df)
has_class <- pred_set$has_class
has_co <- pred_set$has_co

quit_set <- impose_quit(has_class)

# summarize quit counts
summarize_followup(quit_set)
quit_set <- quit_set %>% select(-co_1year)

# main

quit_split <- initial_split(quit_set, prop = 0.8, strata = "quit_verified")
quit_train <- training(quit_split)
quit_test <- testing(quit_split)

return_counts(quit_train, quit_test)


quit_fit <- fit_procedure(quit_train, quit_test)
save(quit_fit, file = "../models/diagnostic/quit_predict_logistic.rda")
  
```


```{r}


metrics <- data.frame()
rocs <- data.frame()
for (f in 1:length(quit_fit)) {
  
  # elastic net results
  nme <- names(quit_fit[f])
  cv_roc_mean <- mean(quit_fit[[f]]$cv$cv_metrics$mean)
  cv_roc_se <- sd(quit_fit[[f]]$cv$cv_metrics$std_err)
  test_auc <- quit_fit[[f]]$test_score$.estimate
  auc_pval <- quit_fit[[f]]$auc_pval
  
  tmp <- data.frame(nme, cv_roc_mean, cv_roc_se, test_auc, auc_pval)
  names(tmp)[names(tmp) == ".estimate"] <- "test_auc"
  metrics <- rbind(metrics, tmp)
  
}
```


```{r}
metrics
```

