---
title: "Growth Curve Prediction"
output: html_notebook
---


```{r}
source('../R/models/predict_class_ordinal.R')
source('../R/models/predict_class_results_ord.R')
source('../R/visualization/visualize.R')

loadRData <- function(fileName){
#loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}
```

```{r}
load("../data/processed/pred_imputedord.rda")

m3_covariate <- loadRData('../data/diagnostic/covariate/lca3_predict.rda')
m3_randomeffects <- loadRData('../data/diagnostic/random_effect/lca3_predict.rda')
m3_propchange <- loadRData('../data/predicted/lca3_predict.rda')
```


```{r}
fit_prediction_model <- function(traj, pred_imputed, fpath='../models/diagnostic/model.rda') {

  df_imputed <- join_lca(traj, pred_imputed)
  df_imputed_split <- initial_split(df_imputed, prop = 0.8)
  imputed_train <- training(df_imputed_split)
  imputed_test <- testing(df_imputed_split)
  
  # train
  
  imputed_train_split <- split_df(imputed_train)
  imputed_test_split <- split_df(imputed_test)
  
  print(return_counts(imputed_train_split, imputed_test_split))
    
  imputed_fits <- fit_procedure(imputed_train_split, imputed_test_split)
  save(imputed_fits, file = fpath)
  
  return(imputed_fits)
}

```


```{r}
m3_covariate_fit <- fit_prediction_model(m3_covariate, pred_imputed, fpath='../models/diagnostic/m3_covariate_enet.rda')
```

```{r}
load('../models/diagnostic/m3_covariate_enet.rda')
  
metrics <- data.frame()
coefs <- data.frame()
rocs <- data.frame()
options(scipen = 999)
for (f in 1:length(imputed_fits)) {
  # enet metrics
  nme <- names(imputed_fits[f])
  cv_auc_mean <- imputed_fits[[f]]$cv$cv_metrics$mean[2]
  cv_auc_se <- imputed_fits[[f]]$cv$cv_metrics$std_err[2]
  test_auc <- imputed_fits[[f]]$test_score$.estimate
  null_auc_mean <- mean(imputed_fits[[f]]$null_aucs)
  # mw_u_u <- imputed_fits[[f]]$mw_u$u
  mw_u_p <- imputed_fits[[f]]$mw_u$p
  
  tmp <- data.frame(nme, cv_auc_mean, cv_auc_se, test_auc, null_auc_mean, mw_u_p)
  metrics <- rbind(metrics, tmp)
  
  # ols coefficients
  # 
  # coefs_df <- tidy(imputed_fits[[f]]$log_fit, exponentiate = TRUE, conf.int = TRUE)
  # coefs_df$model <- nme
  # 
  # coefs <- rbind(coefs, coefs_df)
  roc_tmp <- imputed_fits[[f]]$test_roc
  roc_tmp$model <- nme
  rocs <- rbind(rocs, roc_tmp)
}
```


```{r}
metrics
```




```{r}

```





```{r}
# cv_coef <- gather_cv_coef(imputed_fits, use_ref = FALSE)
# 
#   plot(
#     1 - rocs$specificity, rocs$sensitivity,
#     # type = "S",
#     type='o',
#     col = factor(rocs$model),
#     xlab = "False Positive Rate",
#     ylab = "True Positive Rate",
#     asp = 1
#   )
#   
#   legend("topleft",
#        legend = levels(factor(rocs$model)),
#        pch = 19,
#        col = factor(levels(factor(rocs$model))))
```


